### ISSUE TITLE
Sync-Rework II Issue

### ISSUE THREAD

**Issue by daron666** [ScorexFoundation/Scorex#152]
Found some strange behaviour between two running nodes.
It looks like for each sync request we get 2 answers from 1 node.
That is the reason for warnings like
`[2-Hop-akka.actor.default-dispatcher-2] >> [WARN ] examples.hybrid.HybridNodeViewHolder >> 16:21:48.003 Received modifier 99aQPCZfUYc68nrvQtEH7PJ5RVv28abBWECaMce2bttL that is already in history`

Full log
```

**Comment by daron666** [comment]
Another suspicious messages, they appeared only on second node with `settings2.conf`

```
[2-Hop-akka.actor.default-dispatcher-40] >> [WARN ] e.hybrid.history.HybridHistory >> 16:29:32.003 Found chain without ids form remote
[2-Hop-akka.actor.default-dispatcher-40] >> [WARN ] e.hybrid.history.HybridHistory >> 16:29:32.003 CompareNonsense: List(9QtaztQpSXtVE25yKDiBkH72FafrKqydDREU4DAHxRi, 8o9fQU2Vncv7hCZ18qkJKuWu1aokrheXh2Xiqf2j5wd, 14byW9KrZ7h6QBoiC2xRBc3Dh1MmBH99dpSMCVsAamL4, FbKBT5mEKoHSBo6pZu19A7aY8dCow79X5hwbtwbQ7RG, LsCjArFUkqTDpbmrGiSPzideM51KJNuvichkjxxE7Qf, XvBLUBycnCV1RskQsWqQ91WFcUfUUZ5zYg512ovXRkp, KFJZoNWFGMPDqPAq3k36cRjK7u2mD6Bouru4vEVQUAv, X5F7sass1egDBrocTop3a9cZnjZPUsW8GrCnn7vLqqh, JidjTnawK73ruE5qpEbETBF2jm3UheFSvEEBZnqiM17, 9Ef9KCd5uQc3JVJJbLaS5DC1Ev9RiwZfyfDmitx9xoK, ULjgnfPBzQsm7CMWFnZdkb9FsvKhqf6hmuDumMZ1WbJ, DpPARRuNQKduTdaH7sRZC2JV7GjT5cRRyc9GH1ybnRG, PFFbuwKfKDCDWbwJkxsiqMJ4QiYjv48Si77dfvKj5CU, Bw8pqY1rh7juaCX3WHsfzu4eXszEQJmUsFAjYtdg65s, PyMix3jpY6F866xMkTmuSs7BoVEszBa6yMzYmTipjRk, 7vMfT6Qr93tQGKYPUFGMmAPTxmYXSPKpFrKQ4HX5chU, 95GRrE5wxbp74CdEDAL7NR4CKbdZWKj5HHDabZGdYfS, DMfeJNPA1jnF412a13BE3UaqVaBihoRKF9ysfCjEipr, 17MpqsMyYhGLE2g5kwdqxfEQFASwoDgsLf8Znjv1urj, EusEazEAP1Ry42mhgfDP72czAd9eGaNs3rCjRkPGMjf, 7jS7nuBZ4aUg12umGjLnibyL4U8tsKNmGJv2qegs6aw, 6XC8hksydunAsu8hgbeYfK1sKVbeDqKQ88U5zzfBxpy, 6cS5HecMa3n2cpZG8oySYczGv5sHWASDbzDzNDDEKpS, 5H2gG7aBrYWYzEcjbLVB1MRTW2dk7T4UawdrWsJs3R6, 13JfcaRcbPVLJemqb8t7NMtxFq2YgKLDBNu5sGCxcVgg, CMCnqFntdwH7R6AxC51LDvqjSxRrCacHFffp1aT85kW, 519ij1rKwGpvxx56qXAQL5oyC8FLJjWwLq71r285SpF, B98jYjwanJt169bQAxpfuUqXtzRxjq4P5pHmwBhXdMp, 1ohwtfcjkqXwZFbDjpUkfdAfSvgsnGeUWMdgSDrZSeM, ACwwGsQm9TjUevEguAmqBb2hBYy3rj2yPPNpMEAdzSN, 1Zz6jBW2M6jfhwL1ebiX5nvMXe48d2iwAjN4wAUTQhw, 14YwEUqE3qSeULHcakifVPb41w1kW4D2DaeyatdzaTfn, DSxdQPgvneUPXcL1pEAKkSJbYmKFkuggm4GQz9AWzZJ, AWyccKQy8AUBA398RMocp6RASSR31cGAgKKjiP2Dhnp, 5EQw4dMsYmae8oWMNkZhqWLPAj7pgXwt1J4XAQSMCHA, 57frahhMayqMj2UtbqSGvW4kaWfEu24vjzHoGF4wA6E, 5EBGCPAE51nKEhwyQpNfBPPnfeMP5GGCLoE2ne2mNHz, 1scXnnnKJA8rerDay27nRoe83YWHRQShhLxzRMoZ9Y3, 8MNCZ3PsXPikvu5jJ2Kt6wQ7NWQMx3DLHiiZQ4sdyzz, 7EtWeKiSK8G955nukgz9yjKthmgE4oU8K95S8dBsWRE, 7ZRVtFiWKEZrHZa8a6wCsMCvyn6DrheSEKNVW12bZLh, 7RGe6Yve6L5di1VWHGwbc778g4Nu2mE8mVN5PTT3sYn, 1bfiUHGktaGDQRLQWg3mWK5UMkpzdLr4eYSVMvrVCHE, 14HnkU8nMxz1L6zUWe7YovFikDvcaBp7FrKZ8BMKRpfx, 7txJ5DtP1brZ9i6rBn6K4ZU92sx3XrCsBhkpNgDjyUF, 123vfHPg5QdRDAwyxyvdfqVDEt2tL1igQXLRQTSr1zJy, 1Ciay3YTsNUDLCQNsAHAxGfRG49CPcAVCwQk2ScozLH, 5LwfBiQcYnPP5ugSBtma2CzsefERQJ36mjnQxEJuz1x, 134U2bXQqYfsMB5AqtLFB3K94puTPeArWGkJ8DotrQAQ, 13ffWirXsfPYsNA44YzbsokL7nE6MYX99fhW6dZXWNx7) at height 2}
[2-Hop-akka.actor.default-dispatcher-40] >> [WARN ] s.core.network.NodeViewSynchronizer >> 16:29:32.004 Got nonsense
```

**Comment by kushti** [comment]
both issues are unlikely linked to the "sync-rework" PR, so I've changed the issue's title

**Comment by ceilican** [comment]
When running a single node for a while, the following warning is eventually issued:
```
[info] [2-Hop-akka.actor.default-dispatcher-5] >> [WARN ] scorex.core.network.SyncTracker >> 09:51:37.262 Time to clear status for /127.0.0.2:9088, but it is not found
```

**Comment by ceilican** [comment]
Then, when starting the second node, the following error occurs:

```
[info] [2-Hop-akka.actor.default-dispatcher-4] >> [INFO ] scorex.core.network.UPnP >> 09:54:21.705 Looking for UPnP gateway device...
[info] [scala-execution-context-global-15] >> [INFO ] s.core.utils.NetworkTimeProvider >> 09:54:21.850 New offset adjusted: Some(10)
[info] [2-Hop-akka.actor.default-dispatcher-4] >> [INFO ] scorex.core.network.UPnP >> 09:54:21.941 External IP address is XXX.XXX.XXX.XXX
[info] [2-Hop-akka.actor.default-dispatcher-4] >> [INFO ] s.core.network.NetworkController >> 09:54:22.179 Declared address: None
[info] [2-Hop-akka.actor.default-dispatcher-4] >> [INFO ] s.core.network.NetworkController >> 09:54:22.229 Registering handlers for List((1,GetPeers message), (2,Peers message))
[info] [2-Hop-akka.actor.default-dispatcher-4] >> [ERROR] s.core.network.NetworkController >> 09:54:22.266 Network port 9088 already in use!
[info] [ERROR] [02/05/2018 09:54:22.267] [2-Hop-akka.actor.default-dispatcher-3] [akka://2-Hop/system/IO-TCP/selectors/$a/0] Bind failed for TCP channel on endpoint [/127.0.0.2:9088]
[info] java.net.BindException: Can't assign requested address
[info] 	at sun.nio.ch.Net.bind0(Native Method)
[info] 	at sun.nio.ch.Net.bind(Net.java:433)
[info] 	at sun.nio.ch.Net.bind(Net.java:425)
[info] 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
[info] 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
[info] 	at akka.io.TcpListener.liftedTree1$1(TcpListener.scala:56)
[info] 	at akka.io.TcpListener.<init>(TcpListener.scala:53)
[info] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[info] 	at akka.util.Reflect$.instantiate(Reflect.scala:65)
[info] 	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
[info] 	at akka.actor.Props.newActor(Props.scala:213)
[info] 	at akka.actor.ActorCell.newActor(ActorCell.scala:563)
[info] 	at akka.actor.ActorCell.create(ActorCell.scala:589)
[info] 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)
[info] 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
[info] 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
[info] 	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
[info] 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
[info] 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[info] 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
[info] 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[info] 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
[info] [INFO] [02/05/2018 09:54:22.627] [2-Hop-akka.actor.default-dispatcher-3] [akka://2-Hop/user/networkController] Message [scorex.core.network.NetworkController$RegisterMessagesHandler] from Actor[akka://2-Hop/user/$f#-1878133751] to Actor[akka://2-Hop/user/networkController#-1630527734] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

**Comment by ceilican** [comment]
And I was able to reproduce the warnings mentioned by @daron666 .

**Comment by ceilican** [comment]
After adding a third node, the second node continued issuing the "Got nonsense" warning from time to time. Strangely, only the second node does this. The first and and third node don't.

**Comment by ceilican** [comment]
After adding a fourth node, the first node eventually showed this warning:

```
[info] [2-Hop-akka.actor.default-dispatcher-24] >> [WARN ] e.hybrid.history.HybridHistory >> 10:29:09.913 Found chain without ids form remote
[info] [2-Hop-akka.actor.default-dispatcher-24] >> [WARN ] s.core.network.NodeViewSynchronizer >> 10:29:09.913 Extension is empty while comparison is younger
[info] [2-Hop-akka.actor.default-dispatcher-24] >> [WARN ] s.core.network.NodeViewSynchronizer >> 10:29:09.914 extOpt is empty for: ConnectedPeer(localhost/127.0.0.1:55491). Its status is: Younger.
```

Node 4, like Node 2 also issues "Got Nonsense" warnings periodically.

**Comment by ceilican** [comment]
Node 5 also issues "Got nonsense" warnings periodically.

**Comment by ceilican** [comment]
It seems that, the more nodes I add, the more likely it is for a node N > 1 to emit "Got nonsense" warnings, and the more frequently node 1 emits "already in history" and "extOpt empty" warnings.

**Comment by ceilican** [comment]
@kushti, could you tell us whether this behaviour is normal? Is there something here that needs to be fixed?
