### ISSUE TITLE
versionID is already used during restart of a HybridApp node

### ISSUE THREAD

**Issue by zihehuang** [ScorexFoundation/Scorex#19]
Hello there,

I am encountering an issue of nodes not being able to restore its state after restart. I was able to replicate this issue by doing the following: 
1. Clear the /tmp/scorex/ directory
2. Start a node with HybridApp and wait for generation of several blocks
3. Ctrl+C in the terminal
4. Restart the node
and the error I am getting is following:

```
[ERROR] [03/16/2017 16:50:03.284] [2-Hop-akka.actor.default-dispatcher-4] [akka://2-Hop/user/$b] versionID is already used
akka.actor.ActorInitializationException: akka://2-Hop/user/$b: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:175)
	at akka.actor.ActorCell.create(ActorCell.scala:607)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at akka.util.Reflect$.instantiate(Reflect.scala:65)
	at akka.actor.ArgsReflectConstructor.produce(IndirectActorProducer.scala:96)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:562)
	at akka.actor.ActorCell.create(ActorCell.scala:588)
	... 9 more
Caused by: java.lang.IllegalArgumentException: versionID is already used
	at io.iohk.iodb.LSMStore.update(LSMStore.scala:370)
	at examples.hybrid.history.HistoryStorage.update(HistoryStorage.scala:91)
	at examples.hybrid.history.HybridHistory.$anonfun$append$1(HybridHistory.scala:110)
	at scala.util.Try$.apply(Try.scala:209)
	at examples.hybrid.history.HybridHistory.append(HybridHistory.scala:99)
	at examples.hybrid.HybridNodeViewHolder.genesisState(HybridNodeViewHolder.scala:69)
	at scorex.core.NodeViewHolder.$anonfun$nodeView$1(NodeViewHolder.scala:55)
	at scala.Option.getOrElse(Option.scala:121)
	at scorex.core.NodeViewHolder.$init$(NodeViewHolder.scala:55)
	at examples.hybrid.HybridNodeViewHolder.<init>(HybridNodeViewHolder.scala:18)
	... 18 more
```

5. Further requests to Swagger UI respond with `There was an internal server error.` and no blocks will be generated

**Comment by catena2w** [comment]
Fixed, thank you for bug report!
