### ISSUE TITLE
Concurrent requests to TimeProvider

### ISSUE THREAD

**Issue by catena2w** [ScorexFoundation/Scorex#248]
Our test logs (https://travis-ci.org/ergoplatform/ergo/builds/382548260#L3349) sometimes provide often 
 offset update that should never happen
```
scala-execution-context-global-14] >> [WARN ] s.core.utils.NetworkTimeProvider >> 08:19:40.759 Problems with NTP: 
java.net.SocketTimeoutException: Receive timed out
	at java.base/java.net.PlainDatagramSocketImpl.receive0(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:180)
	at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:814)
	at org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:91)
	at org.apache.commons.net.ntp.NTPUDPClient.getTime(NTPUDPClient.java:113)
	at scorex.core.utils.NetworkTimeProvider.$anonfun$updateOffset$1(NetworkTime.scala:31)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:12)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:283)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1603)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
[scala-execution-context-global-14] >> [INFO ] s.core.utils.NetworkTimeProvider >> 08:19:40.822 New offset adjusted: -2
[scala-execution-context-global-14] >> [INFO ] s.core.utils.NetworkTimeProvider >> 08:19:40.884 New offset adjusted: -1
[scala-execution-context-global-14] >> [INFO ] s.core.utils.NetworkTimeProvider >> 08:19:40.946 New offset adjusted: -1
[scala-execution-context-global-14] >> [INFO ] s.core.utils.NetworkTimeProvider >> 08:19:41.008 New offset adjusted: -1
[scala-execution-context-global-14] >> [INFO ] s.core.utils.NetworkTimeProvider >> 08:19:41.070 New offset adjusted: -1
[scala-execution-context-global-14] >> [INFO ] s.core.utils.NetworkTimeProvider >> 08:19:41.135 New offset adjusted: 0
[scala-execution-context-global-14] >> [INFO ] s.core.utils.NetworkTimeProvider >> 08:19:41.232 New offset adjusted: 1
[scala-execution-context-global-14] >> [INFO ] s.core.utils.NetworkTimeProvider >> 08:19:41.325 New offset adjusted: 13
```

**Comment by catena2w** [comment]
Fixed in https://github.com/ScorexFoundation/Scorex/pull/247
