### ISSUE TITLE
"WARN  [tor.default-dispatcher-10] o.e.n.ErgoDeliveryTracker - Unexpected error" similar warning appearing frequently

### ISSUE THREAD

**Issue by martin-mx** [ScorexFoundation/Scorex#266]
22:31:32.366 WARN  [tor.default-dispatcher-10] o.e.n.ErgoDeliveryTracker - Unexpected error
java.util.NoSuchElementException: key not found: (WrappedArray(0, 34, 27, -92, -111, 51, -122, 33, -50, 25, -43, -101, 94, 20, -1, 28, 86, -22, 123, 18, -121, -89, 111, -37, -109, 67, 30, 118, -106, -49, 78, -24),ConnectedPeer(209.97.138.187/209.97.138.187:9002))
	at scala.collection.MapLike.default(MapLike.scala:232)
	at scala.collection.MapLike.default$(MapLike.scala:231)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.mutable.HashMap.apply(HashMap.scala:65)
	at scorex.core.network.DeliveryTracker.stopExpecting(DeliveryTracker.scala:65)
	at scorex.core.network.DeliveryTracker.$anonfun$reexpect$1(DeliveryTracker.scala:54)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.Try$.apply(Try.scala:209)
	at scorex.core.network.DeliveryTracker.tryWithLogging(DeliveryTracker.scala:95)
	at scorex.core.network.DeliveryTracker.reexpect(DeliveryTracker.scala:53)
	at scorex.core.network.NodeViewSynchronizer$$anonfun$checkDelivery$1.applyOrElse(NodeViewSynchronizer.scala:276)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:172)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at scorex.core.network.NodeViewSynchronizer.aroundReceive(NodeViewSynchronizer.scala:29)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:588)
	at akka.actor.ActorCell.invoke(ActorCell.scala:557)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by kushti** [comment]
Fixed by DeliveryTracker rewrite https://github.com/ScorexFoundation/Scorex/pull/267
