### ISSUE TITLE
 Invalid packet length

### ISSUE THREAD

**Issue by catena2w** [ScorexFoundation/Scorex#299]
We fixed similar bug in https://github.com/ScorexFoundation/Scorex/issues/288, but looks like problem still exists: 
```
[ERROR] [07/27/2018 12:33:25.175] [ergoref-akka.actor.default-dispatcher-8] [akka://ergoref/user/networkController/$a] Invalid packet length: 2747492
java.lang.Exception: Invalid packet length: 2747492
	at scorex.core.network.Buffering.multiPacket$1(Buffering.scala:37)
	at scorex.core.network.Buffering.getPacket(Buffering.scala:48)
	at scorex.core.network.Buffering.getPacket$(Buffering.scala:27)
	at scorex.core.network.PeerConnectionHandler.getPacket(PeerConnectionHandler.scala:53)
```

**Comment by RatanRSur** [comment]
Hi!

How can I repro this? I can't find this error in Scorex's tests or ergo's tests

**Comment by kushti** [comment]
Likely fixed
